version: '3.9'
services:
  mysql:
    image: mysql:9
    container_name: minxi
    restart: always
    environment:
      MYSQL_USER: "minxiUser"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "minxi"
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
    ports:
      - "3006:3006"
    volumes:
      - minxi:/var/lib/mysql
  
  backend:
    build: ./backend
    container_name: nest-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    ports:
      - 3000:3000
  
  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  minxi: